services:
  # Backend API service
  - type: web
    name: recipe-optimizer-api
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URI
        fromDatabase:
          name: recipe-optimizer-db
          property: connectionString
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 11520 # 8 days
      - key: BACKEND_CORS_ORIGINS
        value: '["https://recipe-optimizer.netlify.app"]'

  # Frontend service
  - type: web
    name: recipe-optimizer-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://recipe-optimizer-api.onrender.com/api/v1
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: recipe-optimizer-db
    databaseName: recipe_optimizer
    user: recipe_user

databases:
  - name: recipe-optimizer-db
    databaseName: recipe_optimizer
    user: recipe_user
